//관리자
CREATE TABLE ADMIN(
   ADMINID VARCHAR2(20) PRIMARY KEY,
   ADMINPASS VARCHAR2(20) NOT NULL,
   ADMINNAME VARCHAR2(20) NOT NULL
);

//회원
CREATE TABLE MEMBER(
   MEMBERID VARCHAR2(20) PRIMARY KEY,
   MEMBERPASS VARCHAR2(20) NOT NULL,
   MEMBERNAME VARCHAR2(20) NOT NULL,
   MEMBERADDRESS VARCHAR2(300) NOT NULL,
   MEMBERPHONENUM VARCHAR2(20) NOT NULL,
   MEMBEREMAIL VARCHAR2(30) NOT NULL,
   MEMBERPOINT NUMBER(10) DEFAULT 0
);

//상품
CREATE TABLE ITEM(
   ITEMCODE NUMBER(15) NOT NULL,
   ITEMNAME VARCHAR2(30) NOT NULL,
   ITEMMAINPIC VARCHAR2(100) NOT NULL,
   ITEMDETAILPIC VARCHAR2(100) NOT NULL,
   ITEMPRICE NUMBER(10) NOT NULL,
   ITEMCOLOR VARCHAR2(20) NOT NULL,
   ITEMSTOCK NUMBER(10) NOT NULL,
   ITEMTYPE NUMBER(2) NOT NULL,
   ITEMSALES NUMBER(10) DEFAULT 0,
   CONSTRAINT ITEM_PK PRIMARY KEY(ITEMCODE,ITEMCOLOR)
);

//장바구니
CREATE TABLE CART(
   ITEMCODE NUMBER(15) NOT NULL,
   ITEMCOLOR VARCHAR2(20) NOT NULL,
   ITEMNAME VARCHAR2(20) NOT NULL,
   ITEMMAINPIC VARCHAR2(100) NOT NULL,
   MEMBERID VARCHAR2(20) NOT NULL,
   ITEMPRICE NUMBER(10) NOT NULL,
   ITEMQTY NUMBER(5) NOT NULL,
   ITEMTOTAL NUMBER(10) NOT NULL,
   CONSTRAINT CART_PK PRIMARY KEY(ITEMCODE, ITEMCOLOR, MEMBERID),
   CONSTRAINT ITEMCODE_FK FOREIGN KEY(ITEMCODE, ITEMCOLOR) REFERENCES ITEM(ITEMCODE, ITEMCOLOR),
   CONSTRAINT CARTID_FK FOREIGN KEY(MEMBERID) REFERENCES MEMBER(MEMBERID)
);

//주문
CREATE TABLE ORDERITEM(
    ORDERITEMNUM NUMBER(20) PRIMARY KEY,
    ORDERNUM NUMBER(20) NOT NULL,
    MEMBERID VARCHAR2(20) NOT NULL,
    MEMBERNAME VARCHAR2(20) NOT NULL,
   ORDERADDRESS VARCHAR2(300) NOT NULL,
   ORDERPHONENUM VARCHAR2(20) NOT NULL,
    PAYMENTNAME VARCHAR2(20) NOT NULL,
    ITEMCODE NUMBER(15) NOT NULL,
    ITEMCOLOR VARCHAR2(30) NOT NULL,
    ITEMQTY NUMBER(20) NOT NULL,
    ITEMNAME VARCHAR2(20) NOT NULL,
    ITEMPRICE NUMBER(20) NOT NULL,
    ITEMMAINPIC VARCHAR2(100) NOT NULL,
   ORDERDATE DATE DEFAULT SYSDATE,
    ORDERTOTALPRICE NUMBER(20) NOT NULL,
    DELIVERYSTATE VARCHAR2(50) DEFAULT '배송전',

   CONSTRAINT ORDER_FK FOREIGN KEY(MEMBERID) REFERENCES MEMBER(MEMBERID)
);

CREATE SEQUENCE ORDERITEM_SEQ START WITH 1 INCREMENT BY 1 MAXVALUE 999999 CYCLE NOCACHE;


//배송
CREATE TABLE DELIVERY(
   DELIVERYNUM NUMBER(20) PRIMARY KEY,
   ORDERNUM NUMBER(20) NOT NULL,
   DELIVERYPRICE NUMBER(20) NOT NULL,
   DELIVERYDATE DATE DEFAULT SYSDATE+2,
   DELIVERYSTATE VARCHAR2(20) DEFAULT '배송전',
   CONSTRAINT ORDERNUM_FK FOREIGN KEY(ordernum) REFERENCES orderitem(ordernum)
);


//상품 게시판
CREATE TABLE ITEMBOARD (
   ITEMBOARDNUM NUMBER(20) NOT NULL,
   ITEMCODE NUMBER(15) PRIMARY KEY,
   ITEMNAME VARCHAR2(30) NOT NULL,
   ITEMMAINPIC VARCHAR2(100) NOT NULL,
   ITEMDETAILPIC VARCHAR2(100) NOT NULL,
   ITEMPRICE NUMBER(10) NOT NULL,
   ITEMSTOCK VARCHAR2(100) NOT NULL,
   ITEMTYPE NUMBER(2) NOT NULL
);
CREATE SEQUENCE ITEMBOARD_SEQ START WITH 1 INCREMENT BY 1 MAXVALUE 999999 CYCLE NOCACHE;


//공지게시판
CREATE TABLE NOTICEBOARD (
   NOTICENUM NUMBER(20) PRIMARY KEY,
   ADMINID VARCHAR2(20) NOT NULL,
   NOTICETITLE VARCHAR2(100) NOT NULL,
   NOTICECONTENT VARCHAR2(1000) NOT NULL,
   NOTICEREADCOUNT NUMBER(10) NOT NULL,
   CONSTRAINT NOTICEBOARD_ID_FK FOREIGN KEY(ADMINID) REFERENCES ADMIN(ADMINID)
);

CREATE SEQUENCE NOTICEBOARD_SEQ START WITH 1 INCREMENT BY 1 MAXVALUE 999999 CYCLE NOCACHE;

//기타게시판(리뷰/Q&A)
CREATE TABLE ETCBOARD (
   BOARDNUM NUMBER(20) PRIMARY KEY,
   MEMBERID VARCHAR2(20) NOT NULL,
   ITEMCODE VARCHAR2(50),
   REGDATE DATE DEFAULT SYSDATE,
   BOARDTITLE VARCHAR2(100) NOT NULL,
   BOARDCONTENT VARCHAR2(1000) NOT NULL,
   BTYPE NUMBER(2) NOT NULL,
   BNUM NUMBER(20) NOT NULL,
   CONSTRAINT BOARD_ID_FK FOREIGN KEY(MEMBERID) REFERENCES MEMBER(MEMBERID)
);
CREATE SEQUENCE ETCBOARD_SEQ START WITH 1 INCREMENT BY 1 MAXVALUE 999999 CYCLE NOCACHE;
CREATE SEQUENCE QNA_SEQ START WITH 1 INCREMENT BY 1 MAXVALUE 999999 CYCLE NOCACHE;
CREATE SEQUENCE REVIEW_SEQ START WITH 1 INCREMENT BY 1 MAXVALUE 999999 CYCLE NOCACHE;

//댓글
CREATE TABLE COMMENTS(
   COMMENTSBOARDNUM NUMBER(10) PRIMARY KEY,
   BNUM NUMBER(20) NOT NULL,
   BTYPE NUMBER(3) NOT NULL,
   WRITER VARCHAR2(20) NOT NULL,
   CONTENT VARCHAR2(200) NOT NULL
);

CREATE SEQUENCE COMMENTS_SEQ START WITH 1 INCREMENT BY 1 MAXVALUE 999999 CYCLE NOCACHE;